# VCEEnc
# continuous integration settings

image: Visual Studio 2019

platform:
 - Win32
 - x64

configuration:
 - RelStatic

branches:
  only:
    - master

skip_non_tags: true

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 15
  - ps: Restart-Computer
  - ps: Start-Sleep -s 15
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  - curl -o "nasminst.exe" https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-installer-x86.exe
  - start /wait nasminst.exe /S
  - set PATH=C:\Program Files (x86)\nasm;%PATH%
  - nasm --version

before_build:
  - git clone https://github.com/vapoursynth/vapoursynth.git ..\vapoursynth
  - git clone -b MT https://github.com/pinterf/AviSynthPlus.git ..\avisynthplus
  - git clone https://github.com/KhronosGroup/OpenCL-Headers.git ..\openclheaders
  - git clone https://github.com/maki-rxrz/Caption2Ass_PCR.git ..\caption2ass
  - for /f "usebackq tokens=*" %%i IN (`cd`) DO @set CURRENT_DIR=%%i
  - set AVISYNTH_SDK=%CURRENT_DIR%\..\AviSynthPlus\avs_core
  - set VAPOURSYNTH_SDK=%CURRENT_DIR%\..\vapoursynth
  - set OPENCL_HEADERS=%CURRENT_DIR%\..\openclheaders
  - set CAPTION2ASS_SRC=%CURRENT_DIR%\..\caption2ass\src
  - echo %CURRENT_DIR%
  - echo %PLATFORM%
  - echo %CONFIGURATION%
  - echo %AVISYNTH_SDK%
  - echo %VAPOURSYNTH_SDK%
  - echo %OPENCL_HEADERS%
  - echo %CAPTION2ASS_SRC%
  - ps: |
      $version = $null
      if (Test-Path Env:APPVEYOR_REPO_TAG_NAME)
      {
          $version = (Get-Item Env:APPVEYOR_REPO_TAG_NAME).Value
      }
      
      if ([string]::IsNullOrEmpty($version))
      {
          $version = $env:APPVEYOR_BUILD_VERSION + '_Alpha'
      }
      $env:BUILD_VERSION=$version

  - echo %BUILD_VERSION%
  - appveyor UpdateBuild -Version "%BUILD_VERSION%"

build:
  parallel: true
  project: VCEEnc.sln

after_build:
  - mkdir VCEEncC_Release
  - copy _build\%PLATFORM%\%CONFIGURATION%\VCEEncC*.exe VCEEncC_Release
  - copy _build\%PLATFORM%\%CONFIGURATION%\*.dll VCEEncC_Release
  - 7z a -mx9 VCEEncC_%BUILD_VERSION%_%PLATFORM%.7z .\VCEEncC_Release\*

artifacts:
  - path: VCEEncC_%BUILD_VERSION%_%PLATFORM%.7z
    name: VCEEncC_%BUILD_VERSION%_%PLATFORM%

deploy:
  provider: GitHub
  auth_token:
    secure: IDRwZWN1uQaTxb64SQnTDNJR5KPtCFPL3Mln9GrdZ7TSiyec/o1KXpOuh/50ZO5A
  artifact: VCEEncC_%BUILD_VERSION%_%PLATFORM%
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
